-- Script para agregar contenido a los demás libros
USE libronet;

-- Actualizar "Cien años de soledad"
UPDATE libros 
SET contenido_completo = 'Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Macondo era entonces una aldea de veinte casas de barro y cañabrava construidas a la orilla de un río de aguas diáfanas que se precipitaban por un lecho de piedras pulidas, blancas y enormes como huevos prehistóricos. El mundo era tan reciente, que muchas cosas carecían de nombre, y para mencionarlas había que señalarlas con el dedo. Todos los años, por el mes de marzo, una familia de gitanos desarrapados plantaba su carpa cerca de la aldea, y con un grande alboroto de pitos y timbales daban a conocer los nuevos inventos. Primero llevaron el imán. Un gitano corpulento, de barba montaraz y manos de gorrión, que se presentó con el nombre de Melquíades, hizo una truculenta demostración pública de lo que él mismo llamaba la octava maravilla de los sabios alquimistas de Macedonia. Fue de casa en casa arrastrando dos lingotes metálicos, y todo el mundo se espantó al ver que los calderos, las pailas, las tenazas y los anafes se caían de su lugar, y las maderas crujían por la desesperación de los clavos y los tornillos tratando de desenclavarse, y aun los objetos perdidos desde hacía mucho tiempo aparecían por donde más se les había buscado, y se arrastraban en desbandada turbulenta detrás de los fierros mágicos de Melquíades. "Las cosas tienen vida propia -pregonaba el gitano con áspero acento-, todo es cuestión de despertarles el ánima." José Arcadio Buendía, cuya desaforada imaginación iba siempre más lejos que el ingenio de la naturaleza, y aun más allá del milagro y la magia, pensó que era posible servirse de aquella invención inútil para desentrañar el oro de la tierra. Melquíades, que era un hombre honrado, le previno: "Para eso no sirve." Pero José Arcadio Buendía no creía en aquel tiempo en la honradez de los gitanos, así que cambió su mulo y una partida de chivos por los dos lingotes imantados. Úrsula Iguarán, su mujer, que contaba con aquellos animales para ensanchar el desmedrado patrimonio doméstico, no consiguió disuadirlo. "Muy pronto ha de sobrarnos oro para cubrir el suelo", replicó su marido. Durante varios meses se empeñó en demostrar el acierto de sus conjeturas. Exploró palmo a palmo la región, inclusive el fondo del río, arrastrando los dos lingotes de hierro y recitando en voz alta el conjuro de Melquíades. Lo único que logró desenterrar fue una armadura del siglo XV con todas sus partes soldadas por un cascote de óxido, cuyo interior tenía la resonancia hueca de una enorme calabaza llena de piedras. Cuando José Arcadio Buendía y los cuatro hombres de su expedición lograron desarticular la armadura, encontraron dentro un esqueleto calcificado que llevaba colgado en el cuello un relicario de cobre con un rizo de mujer.'
WHERE titulo = 'Cien años de soledad';

-- Actualizar "1984"
UPDATE libros 
SET contenido_completo = 'Era un día luminoso y frío de abril y los relojes daban las trece. Winston Smith, con la barbilla clavada en el pecho en su esfuerzo por burlar el viento desagradable, se deslizó rápidamente por entre las puertas de cristal de las Casas de la Victoria, aunque no con la suficiente rapidez para impedir que una ráfaga de polvo y suciedad se colara con él.

El vestíbulo olía a col hervida y a esteras viejas. En un extremo había un cartel, demasiado grande para estar colgado en el interior, que había sido fijado a la pared. Representaba únicamente un rostro enorme, de más de un metro de ancho: el rostro de un hombre de unos cuarenta y cinco años, con un bigote negro espeso y facciones toscamente atractivas. Winston se dirigió hacia las escaleras. Era inútil intentar el ascensor. Raramente funcionaba, incluso en los mejores momentos, y ahora, en las horas del día, la corriente eléctrica se cortaba como parte de la economía de guerra en preparación para la Semana del Odio. El apartamento estaba en el séptimo piso y Winston, que tenía treinta y nueve años y una úlcera varicosa sobre el tobillo derecho, subió despacio, descansando varias veces en el camino. En cada rellano, frente al tubo del ascensor, el cartel con el rostro enorme te miraba desde la pared. Era uno de esos carteles que están hechos de tal manera que los ojos te siguen cuando te mueves. EL GRAN HERMANO TE VIGILA, decía la leyenda debajo del rostro.

Dentro del apartamento una voz dulce estaba leyendo una lista de cifras que tenían algo que ver con la producción de lingotes de hierro. La voz procedía de una placa oblonga de metal, como un espejo empañado, que formaba parte de la superficie de la pared derecha. Winston giró un dial y la voz se hizo algo más débil, aunque las palabras seguían siendo distinguibles. El instrumento (llamado telepantalla) podía ser atenuado, pero no apagado por completo. Winston se acercó a la ventana: un hombrecillo menudo y frágil, de unos treinta años, con el pelo rubio y el rostro naturalmente rubicundo. Llevaba el uniforme azul del Partido. Sus ojos eran grandes y de un azul muy claro, con una expresión de melancolía que se convertía en una mirada de inexpresividad cuando se fijaba en alguien.

El exterior del edificio, visto desde la ventana, se presentaba sombrío. El viento soplaba en espirales de polvo y papel desgarrado. Aunque el sol brillaba y el cielo era de un azul intenso, todo parecía descolorido excepto los carteles que estaban por todas partes. El rostro de bigote negro te miraba desde cada esquina estratégica. Había uno en la casa de enfrente. EL GRAN HERMANO TE VIGILA, decía la leyenda, mientras los ojos oscuros miraban profundamente a los de Winston. En la calle, otro cartel, desgarrado en una esquina, se agitaba intermitentemente, tapando y destapando la palabra INGSOC. Más lejos, un helicóptero pasó entre los tejados, se cernió un momento como una mosca azul, y luego se alejó con una curva. Era una patrulla que espiaba por las ventanas de la gente. Pero las patrullas no importaban. Solo importaba la Policía del Pensamiento.'
WHERE titulo = '1984';

-- Verificar todos los cambios
SELECT id, titulo, LENGTH(contenido_completo) as longitud_contenido 
FROM libros 
WHERE contenido_completo IS NOT NULL 
ORDER BY id; 